### ISSUE TITLE
Error resolving webpackConfig

### ISSUE THREAD

**Issue by ElliotGilchrist** [benmosher/eslint-plugin-import#1288]
Most rules are working, but some cause eslint to break.
Seems to be looking for my webpack config within node_modules

Here's the error:
```
~/proj/reacttest$ yarn lint
yarn run v1.12.3
$ eslint .
Error resolving webpackConfig { Error: Cannot find module '/home/elliot/proj/reacttest/node_modules/react-router-dom/webpack.dev.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.exports.resolve (/home/elliot/proj/reacttest/node_modules/eslint-import-resolver-webpack/index.js:70:27)
    at v2 (/home/elliot/proj/reacttest/node_modules/eslint-module-utils/resolve.js:94:23)
    at withResolver (/home/elliot/proj/reacttest/node_modules/eslint-module-utils/resolve.js:99:16)
    at fullResolve (/home/elliot/proj/reacttest/node_modules/eslint-module-utils/resolve.js:116:22)
    at Function.relative (/home/elliot/proj/reacttest/node_modules/eslint-module-utils/resolve.js:61:10)
    at remotePath (/home/elliot/proj/reacttest/node_modules/eslint-plugin-import/lib/ExportMap.js:403:30) code: 'MODULE_NOT_FOUND' }
Error: Cannot find module '/home/elliot/proj/reacttest/node_modules/react-router-dom/webpack.dev.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.exports.resolve (/home/elliot/proj/reacttest/node_modules/eslint-import-resolver-webpack/index.js:70:27)
    at v2 (/home/elliot/proj/reacttest/node_modules/eslint-module-utils/resolve.js:94:23)
    at withResolver (/home/elliot/proj/reacttest/node_modules/eslint-module-utils/resolve.js:99:16)
    at fullResolve (/home/elliot/proj/reacttest/node_modules/eslint-module-utils/resolve.js:116:22)
    at Function.relative (/home/elliot/proj/reacttest/node_modules/eslint-module-utils/resolve.js:61:10)
    at remotePath (/home/elliot/proj/reacttest/node_modules/eslint-plugin-import/lib/ExportMap.js:403:30)
error Command failed with exit code 2.
```

package.json:
```json
{
  "dependencies": {
    "babel-runtime": "^6.26.0",
    "eslint-plugin-jsdoc": "^4.1.0",
    "lodash": "^4.17.11",
    "prop-types": "^15.7.2",
    "react": "^16.8.1",
    "react-a11y": "^1.1.0",
    "react-dom": "^16.8.1",
    "react-hot-loader": "^4.6.5",
    "react-router-dom": "^4.3.1",
    "styled-components": "^4.1.3",
    "winston": "^3.2.1"
  },
  "devDependencies": {
    "@babel/cli": "^7.2.3",
    "@babel/core": "^7.2.2",
    "@babel/preset-env": "^7.3.1",
    "@babel/preset-react": "^7.0.0",
    "babel-loader": "^8.0.5",
    "css-loader": "^2.1.0",
    "csv-loader": "^3.0.2",
    "eslint": "^5.13.0",
    "eslint-import-resolver-webpack": "^0.11.0",
    "eslint-plugin-import": "^2.16.0",
    "eslint-plugin-jsx-a11y": "^6.2.1",
    "eslint-plugin-lodash": "^5.1.0",
    "eslint-plugin-react": "^7.12.4",
    "file-loader": "^3.0.1",
    "html-webpack-plugin": "^3.2.0",
    "style-loader": "^0.23.1",
    "webpack": "^4.29.3",
    "webpack-cli": "^3.2.3",
    "webpack-dev-server": "^3.1.14",
    "webpack-merge": "^4.2.1",
    "xml-loader": "^1.2.1"
  },
  "resolutions": {
    "ajv": "6.8.1"
  }
}
```

eslintrc.yml
```yml
env:
  browser: true
  node: true
  es6: true
settings:
  react:
    version: 'detect'
  import/resolver:
    webpack:
      config: 'webpack.dev.js'
extends:
- eslint:recommended
- plugin:react/recommended
- plugin:lodash/recommended
- plugin:jsx-a11y/recommended
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
- react
- import
- lodash
- jsx-a11y
- jsdoc
rules:
  # These rules work as expected
  import/no-unresolved: 'error'
  import/no-dynamic-require: 'error'
  import/no-webpack-loader-syntax: 'error'
  import/no-self-import: 'error'
  import/no-useless-path-segments: 'warn'
  import/export: 'error'
  import/no-extraneous-dependencies: 'warn'
  import/no-mutable-exports: 'error'
  import/first: 'warn'
  import/exports-last: 'warn'
  import/no-duplicates: 'warn'
  import/no-namespace: 'warn'
  import/extensions:
    - warn
    - never
  import/order: 'warn'
  import/newline-after-import: 'warn'
  import/no-unassigned-import: 'error'

  # These rules cause eslint to break :/
  import/named: 'error'
  import/default: 'error'
  import/namespace: 'error'
  import/no-cycle: 'error'
  import/no-named-as-default: 'warn'
  import/no-named-as-default-member: 'warn'
  import/no-deprecated: 'warn'
```

webpack.common.js
```js
const path = require('path')
const webpack = require('webpack')
const HtmlWebpackPlugin = require('html-webpack-plugin')

module.exports = {
  entry: './index.js',
  context: path.resolve(__dirname, 'src'),
  module: {
    rules: [
      // CSS
      { test: /\.css$/, use: ['style-loader', 'css-loader'] },
      // Images
      { test: /\.(png|svg|jpg|gif)$/, loader: 'file-loader' },
      // Fonts
      { test: /\.(woff|woff2|eot|ttf|otf)$/, loader: 'file-loader' },
      // Data
      { test: /\.(csv|tsv)$/, loader: 'csv-loader' },
      // XML
      { test: /\.xml$/, loader: 'xml-loader' },
      // Babel
      {
        test: /\.(js|jsx)$/,
        exclude: /(node_modules|bower_components)/,
        loader: 'babel-loader',
        options: { presets: ['@babel/preset-env'] },
      },
    ],
  },
  resolve: {
    modules: [path.resolve(__dirname, ''), 'node_modules'],
    extensions: ['*', '.js', '.jsx'],
  },
  output: {
    path: path.resolve(__dirname, 'dist'),
    publicPath: '/',
    filename: 'bundle.js',
  },
  plugins: [
    new webpack.HotModuleReplacementPlugin(),
    new HtmlWebpackPlugin({ template: 'index.html' }),
  ],
}

```

webpack.dev.js
```js
const path = require('path')
const merge = require('webpack-merge')
const common = require('./webpack.common.js')

module.exports = merge(common, {
  mode: 'development',
  devtool: 'cheap-eval-source-map',
  devServer: {
    contentBase: path.join(__dirname, 'public/'),
    port: 3000,
    hot: true,
    historyApiFallback: true,
  },
})
```

The error shows `node_modules/react-router-dom`. The error will show up if I import anything from `react-router-dom`. It's not limited that though, I've found it happens when I use `styled-components` as well, so I assume its an issue with my setup here, not with those libraries.
If I change this value, the config name in the error message changes as well:
```yml
#eslintrc.yml
settings:
    webpack:
      config: 'webpack.dev.js'
```

I'm pretty new to webpack so I imagine there's something wrong with my configuration, but I'm having trouble googling or debugging the issue. Thanks in advance :)

**Comment by ElliotGilchrist** [comment]
Fixed by adding 
```yml
settings:
  import/ignore:
    - node_modules
```
to my .eslintrc.yml
