### ISSUE TITLE
no-unused-modules does not work with `export class`

### ISSUE THREAD

**Issue by ehmicky** [benmosher/eslint-plugin-import#1368]
`index.js`:

```js
import { Example } from './foo.js'
export { Example }
```

`foo.js`:

```js
export class Example {}
```

`.eslintrc.yml`:

```yml
parserOptions:
  ecmaVersion: 2019
  sourceType: module
plugins: [import]
rules:
  import/no-unused-modules: [2, {missingExports: true}]
```

Then:

```bash
$ eslint
/home/user/example/foo.js
  1:1  error  No exports found                                 import/no-unused-modules

✖ 1 problem (1 error, 0 warnings)
```

However the following works:

```js
class Example {}
export { Example }
```

`eslint`: `5.16.0`
`eslint-plugin-import`: `2.17.3`
`node`: `12.3.1`
OS: Ubuntu `19.04`
