### ISSUE TITLE
[eslint-import-resolver-node] allow ~/...

### ISSUE THREAD

**Issue by TriMoon** [benmosher/eslint-plugin-import#1454]
Could you add the posibility to use `~` as a replacement for $HOME like in shells?
That way it would be possible to use:
```yaml
settings:
  import/resolver:
    node:
      paths:
        - ~/node_modules
```
instead of hardcoding the real path to the user's home dir, which will be different for every user...
