### ISSUE TITLE
[import/no-cycle] possible false-positive with re-exported names

### ISSUE THREAD

**Issue by silverwind** [benmosher/eslint-plugin-import#1668]
Given these files:

a.js
```js
import {b} from './internal';
export const a = 'a';
```
b.js
```js
import {a} from './internal';
export const b = 'b';
```
internal.js
```js
export * from './a';
export * from './b';
```
.eslintrc
```yaml
plugins:
  - import

parserOptions:
  ecmaVersion: 2020
  sourceType: module

rules:
  import/no-cycle: [2]
```

I see these errors:
```console
a.js
  1:1  error  Dependency cycle detected  import/no-cycle

b.js
  1:1  error  Dependency cycle detected  import/no-cycle

internal.js
  1:1  error  Dependency cycle detected  import/no-cycle
  2:1  error  Dependency cycle detected  import/no-cycle
```

This is a example of @mweststrate's [internal module pattern](https://medium.com/visual-development/how-to-fix-nasty-circular-dependency-issues-once-and-for-all-in-javascript-typescript-a04c987cf0de#9afb) and if I understand correctly, there are no actual circular dependencies here. Is it a false-positive or a error in the pattern itself?
