### ISSUE TITLE
[import/order] Inline comments are not moved by the auto-fixer along with the rest of the line

### ISSUE THREAD

**Issue by astorije** [benmosher/eslint-plugin-import#1723]
Related: https://github.com/benmosher/eslint-plugin-import/issues/1450

### Repro

```tsx
import { Foo } from 'foo';
export { Bar }; // Comment on the export line
```

```yaml
import/order:
  - error
  - pathGroupsExcludedImportTypes:
      - builtin
    newlines-between: always
    alphabetize:
      order: asc
      caseInsensitive: true
```

### Expected

```tsx
import { Foo } from 'foo';

export { Bar }; // Comment on the export line
```

### Actual

```tsx
import { Foo } from 'foo'; // Comment on the export line

export { Bar };
```
