### ISSUE TITLE
import/no-unresolved should work with commonjs by default

### ISSUE THREAD

**Issue by danielo515** [benmosher/eslint-plugin-import#1734]
Hello.
Thank you for this great plugin, really helps me reduce the amount of errors I have.
However, it requires me to configure the no-unresolved rule separatelly to make it work with modules of type commonjs.
I expected that this configuration:

```yaml
extends:
    - plugin:import/errors
    - plugin:import/warning
parserOptions:
    ecmaVersion: 2017
    sourceType: module
    ecmaFeatures:
        spread: true
```

Was all that I may need, but I had to add specific rule configuration like this:

```yaml
rules:
    import/no-unresolved: [2, { commonjs: true }]
```

I think require is common enough to be taken in account by default by just importing the presets. Or at least provide a global setting.

regards
