### ISSUE TITLE
[import/no-extraneous-dependencies] when using typescript `baseUrl` in a monorepo

### ISSUE THREAD

**Issue by loqusion** [benmosher/eslint-plugin-import#2259]
# Repo

##### tree
```
<root>
├── packages
│   └── web
│       ├── .eslintrc.yml
│       └── tsconfig.json
├── .eslintrc.yml
├── package.json
└── tsconfig.json

```

##### tsconfig.json
> Other options are omitted for brevity.
```json
{
  "compilerOptions": {
    "baseUrl": "./packages",
  }
}
```

##### packages/web/tsconfig.json
> Other options are omitted for brevity.
```json
{
  "extends": "../../tsconfig.json",
}
```

##### .eslintrc.yml
> Other options are omitted for brevity.
```yml
parser: '@typescript-eslint/parser'
parserOptions:
  tsconfigRootDir: .
  project: ./tsconfig.json
settings:
  import/resolver:
    node:
      extensions: [.js, .jsx, .ts, .tsx]
    typescript:
      project: packages/*/tsconfig.json
```

#### packages/web/.eslintrc.yml
```yml
parserOptions:
  project: packages/web/tsconfig.json
```

#### packages/web/src/store.ts
```typescript
import appHeaderTitleReducer from 'web/src/layout/appHeaderTitleSlice';
```

# Problem

#### Expected result
It should respect `baseUrl` option on tsconfig.json

#### Actual result
```
error  'web' should be listed in the project's dependencies. Run 'npm i -S web' to add it  import/no-extraneous-dependencies
```

#### Additional info
I tried [this solution](https://github.com/import-js/eslint-plugin-import/issues/1485#issuecomment-535351922), then [this variant](https://github.com/import-js/eslint-plugin-import/issues/1485#issuecomment-830651345) but neither worked.

Everything was working just fine before I started migrating the project to a monorepo.

#### Versions

<table>
<tr>
	<th>package
	<th>version
<tr>
	<td><code>@typescript-eslint/eslint-plugin
	<td><code>4.31.1
<tr>
	<td><code>@typescript-eslint/parser
	<td><code>4.31.1
<tr>
	<td><code>eslint-plugin-import
	<td><code>2.24.0
<tr>
	<td><code>eslint-import-resolver-typescript
	<td><code>2.5.0
<tr>
	<td><code>typescript
	<td><code>4.4.3
<tr>
	<td><code>eslint
	<td><code>7.32.0
<tr>
	<td><code>node
	<td><code>14.17.3
<tr>
	<td><code>npm
	<td><code>6.14.13
<tr>
	<td><code>yarn
	<td><code>1.22.15
</table>
