### ISSUE TITLE
Docs are not clear

### ISSUE THREAD

**Issue by cilphex** [benmosher/eslint-plugin-import#2263]
The docs show how you can override some options with parameters that look like this:

```
settings:
  import/resolver:
    webpack:
      config: 'webpack.dev.config.js'
```

...But it does not say what type of file this is, what it's named, or where it's located. These are settings without any context at all.
