### ISSUE TITLE
[import/consistent-type-specifier-style]: add exceptions

### ISSUE THREAD

**Issue by zkulbeda** [benmosher/eslint-plugin-import#2872]
Typescript 5.0 introduces new option [--verbatimModuleSyntax ](https://devblogs.microsoft.com/typescript/announcing-typescript-5-0/#verbatimmodulesyntax) that has special behavior with inline marker in import statement.
```ts
// Erased away entirely.
import type { A } from "a";

// Rewritten to 'import { b } from "bcd";'
import { b, type c, type d } from "bcd";

// Rewritten to 'import {} from "xyz";'
import { type xyz } from "xyz";
```

So, there are some packages that contain only type declarations and can't be imported by nodejs and will cause errors.

For example:
```ts

// Rewritten to 'import {} from "type-fest";' and will cause import error
import { type EmptyObject } from "type-fest";

// Erased away entirely. Desired behavior.
import type { EmptyObject } from "type-fest";
```

Proposal: add third argument to eslint config for specifying package name exceptions
```yaml
"import/consistent-type-specifier-style": ["error", "prefer-inline", {
    "exceptions": ["**/*/some-file.js", "type-fest"]
}]
```
Autofix should consider exceptions and apply opposite marker option for them.
