### ISSUE TITLE
Weird errors when use inline-loaders to import .scss files into .js/.jsx

### ISSUE THREAD

**Issue by bartsmykla** [benmosher/eslint-plugin-import#769]
Hi.

When I try to import .scss files by using webpacks inline loaders, like:
```js
import variables from '!!sass-variable-loader!../../../components/vars.scss';
```

I'm receiving these errors:
```
  1:1   error    Resolve error: Cannot read property 'toUpperCase' of undefined                                                                   import/no-unresolved
  1:1   error    Resolve error: Cannot read property 'toUpperCase' of undefined                                                                   import/no-extraneous-dependencies
  1:1   warning  Resolve error: Cannot read property 'toUpperCase' of undefined                                                                   import/no-duplicates
  1:1   error    Resolve error: Cannot read property 'toUpperCase' of undefined                                                                   import/extensions
  1:1   error    Resolve error: Cannot read property 'toUpperCase' of undefined                                                                   import/no-absolute-path
  2:1   error    Unexpected '!' in '!!sass-variable-loader!../../../components/vars.scss'. Do not use import syntax to configure webpack loaders  import/no-webpack-loader-syntax
  2:28  error    Unable to resolve path to module '!!sass-variable-loader!../../../components/vars.scss'                                          import/no-unresolved
```

My .eslintrc.yml file:
```yml
---
extends:
  - airbnb
  - airbnb-flow
plugins:
  - react
  - jsx-a11y
  - import
  - immutable
  - flowtype
  - chai-expect
  - chai-friendly
  - sinon
  - redux-saga
globals:
  expect: true
  __apiUrl__: true
  __BROWSER__: true
  __ENV__: true
  __EXTENSION_ID__: true
  __googleOauthUrl__: true
  __signOutFromApiUrl__: true
  __invalidAccessToken__: true
  __websocketsServerUrl__: true
  __apiAuthUrl__: true
rules:
  flowtype/require-parameter-type: 2
  no-console: 2
  # chai-friendly plugin
  no-unused-expressions: 0
  chai-friendly/no-unused-expressions: 2
env:
  browser: true
  node: true
  mocha: true
  webextensions: true
settings:
  import/ignore:
    - .scss$
  import/resolver:
    webpack:
      config: 'webpack.config.js'
```

I can't find another way of using inline-loaders. Did you met these kind of problems yet?

Cheers!
