### ISSUE TITLE
`default` rule not being triggered with webpack resolver

### ISSUE THREAD

**Issue by cannoneyed** [benmosher/eslint-plugin-import#780]
When the `default` rule is applied, the resolved module with my current webpack setup is always evaluated as `null` [here](https://github.com/benmosher/eslint-plugin-import/blob/master/src/rules/default.js#L22)

```javascript
// src/rules/default.js
var imports = Exports.get(node.source.value, context)
if (imports == null) return
```

Since the imports variable is always `null`, the `default` rule never gets a chance to be evaluated.

For whatever reason, I can't figure out which combination of resolvers / webpack settings to use to get my modules to load correctly in the plugin... Any insight would be greatly appreciated!

Current eslintrc.yml
```yaml
parser: 'babel-eslint'
ecmaFeatures:
    modules: true
    jsx: true
parserOptions:
    ecmaFeatures:
        jsx: true
        experimentalObjectRestSpread: true
    sourceType: 'module'
    ecmaVersion: 6
env:
    browser: true
    es6: true
    jest: true
    node: true
plugins: [ 'react', 'import' ]

settings:
    import/resolver:
        webpack:
            config: './webpack.dev.js'
...
```
