### ISSUE TITLE
Overriding 

### ISSUE THREAD

**Issue by dschinkel** [benmosher/eslint-plugin-import#887]
I'm struggling to figure out how to use your lib here to extend my existing eslintrc.json that lives at the root of my app.  I want to override in an eslintrc.js file that I added to my /src/test folder.

eslintrc.json

```
{
  "extends": [
    "airbnb",
    "eslint:recommended",
    "plugin:react/recommended",
    "plugin:import/errors"
  ],
  "plugins": ["react"],
  "parser": "babel-eslint",
  "parserOptions": {"ecmaFeatures": {"jsx": true}},
  "env": {"mocha": true},
..etc
```

`src/test/eslintrc.js` - this is what I'm having trouble with.  How to use your module and then specify `'import/no-extraneous-dependencies': ,` in it:
```
---
extends:
  plugins:
    - import
  rules:
    import/no-extraneous-dependencies: ["error", { devDependencies: true, }]
```

I'm using webstorm and so I'm pointing the WebStorm eslint setttings to my ./eslintrc.json file.  But it's not able to compile my eslintrc.js file, it complains about the syntax.  What am I missing here?
