### ISSUE TITLE
import/named: wildcard export not working?

### ISSUE THREAD

**Issue by wmertens** [benmosher/eslint-plugin-import#920]
Simplified version:
a.js:
```
    export const a = 5
```
b.js:
```
    export * from './a'
```
c.js:
```
    import {a} from './b' 
```
c.js errors with `import/named: export a not found in b.js`

however, when I try this simplified version, there is no error for c but it also doesn't error if I import `x` which definitely doesn't exist. So not sure what is going on…

**Comment by ljharb** [comment]
`*` imports/exports cause all kinds of complexity; i'm sure this plugin probably just doesn't follow the ModuleRecords through transitively.

**Comment by ThiefMaster** [comment]
I have the same problem.

**Comment by bradennapier** [comment]
yeah happening here as well.  I swear i use this all the time but in the latest iterations its def not working anymore!

My current setup is about as simple as shown above

**Comment by bitcrumb** [comment]
This still seems to be an issue. But it is not *consistently* an issue, since we are using this pattern everywher in our codebase. So it only seems to trigger in certain situations?

**Comment by msteitle** [comment]
Also having this issue.

**Comment by benmosher** [comment]
I was having this issue and fixed it by adding the [TS resolver](https://github.com/alexgorbatchev/eslint-import-resolver-typescript) after Webpack:

```yaml
settings:
  import/resolver:
    webpack: {}
    typescript: {}
  import/extensions: ['.js', '.ts', '.tsx']
  import/ignore: ['node_modules', 'src/js/', 'private_modules']
  import/parsers: {
    '@typescript-eslint/parser': ['.ts', '.tsx']
  }
```

I also thought it didn't work anywhere but it was specifically when it was outside of the areas for which I have webpack config.

So while I also initially thought it was a bug in the rule I think it was just due to resolution issues.

FWIW [this test](https://github.com/benmosher/eslint-plugin-import/blob/master/tests/src/rules/named.js#L29) is specifically for `export * from ...` so this rule is definitely supposed to handle this. But if it can't resolve the deep file from the shallow file, you'll see things like you're seeing.
